version: "3.8"

services:
    app:
        build: .
        container_name: ifort-laravel
        ports:
            - "8080:80"
        environment:
            APP_ENV: local
            APP_DEBUG: "1"
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
            MIGRATE_ON_BOOT: "true"
            SEED_ON_BOOT: "true"
        volumes:
            - .:/var/www/html
